[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ["node_modules", "lib"]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@uniswap/=node_modules/@uniswap/',
    'base64-sol/=node_modules/base64-sol/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'solmate/=node_modules/solmate/',
]
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports_ignore = ["Merkle"]
