[profile.default]
src = 'contracts'
test = 'test/foundry'
out = 'out'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    '@chainlink/=node_modules/@chainlink/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@eth-optimism/=node_modules/@eth-optimism/',
    '@manifoldxyz/=node_modules/@manifoldxyz/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@pooltogether/=node_modules/@pooltogether/',
    '@uniswap/=node_modules/@uniswap/',
    'base64-sol/=node_modules/base64-sol/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'solmate/=node_modules/solmate/',
]
gas_reports_ignore = ["Merkle"]
solc = '0.8.17'
optimizer = true
optimizer_runs = 1_000_000
via_ir = false
sparse_mode = true

[profile.fast]
via_ir = false
optimizer = false

[profile.fast.optimizer_details]
inliner = false
deduplicate = false
cse = false
