# Script name
name: Contract Tests

# Prerequisites for execution: any actions with the pool-request
on: [pull_request]

# Task list
jobs:
  test:
    # Task name
    name: Compile contracts & run tests

    # Run on a virtual machine with Ubuntu
    runs-on: ubuntu-latest

    # List of steps
    steps:
      # Use project code from a specific commit
      # By default, the branch whose changes caused the script to run is used
      - uses: actions/checkout@v3

      # Configuring Node.js 14 to run on a virtual machine
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # The described bash commands will be executed
      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        run: |
          CURVE_TYPE=linear npx hardhat test
          CURVE_TYPE=exponential npx hardhat test
