# Script name
name: Contract Tests

# Prerequisites for execution: any actions with the pool-request
on: [pull_request]

# Task list
jobs:
  compile:
    # Task name
    name: Compile contracts

    # Run on a virtual machine with Ubuntu
    runs-on: ubuntu-latest

    # List of steps
    steps:
      # Use project code from a specific commit
      # By default, the branch whose changes caused the script to run is used
      - uses: actions/checkout@v3

      # Configuring Node.js 18 to run on a virtual machine
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      # The described bash commands will be executed
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Cache Hardhat Artifacts
        id: cache-artifacts-hardhat
        uses: actions/cache@v3
        with:
          path: |
            artifacts
            cache
            typechain-types
          key: artifacts-${{ runner.os }}-hardhat-${{ hashFiles('contracts') }}

      - name: Compile Contracts
        if: steps.cache-artifacts-hardhat.outputs.cache-hit != 'true'
        run: TESTING=true yarn compile
  test:
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        curve: [linear, exponential, sigmoid]
    steps:
      - uses: actions/checkout@v3

      # Configuring Node.js 18 to run on a virtual machine
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      # The described bash commands will be executed
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Cache Hardhat Artifacts
        id: cache-artifacts-hardhat
        uses: actions/cache@v3
        with:
          path: |
            artifacts
            cache
            typechain-types
          key: artifacts-${{ runner.os }}-hardhat-${{ hashFiles('contracts') }}

      - name: Run Tests
        run: CURVE_TYPE=${{ matrix.curve }} yarn test:hh --parallel
